/** Metrics header for a showcase repo - a glass-chrome strip of numbers. */

import { GitCommit, Clock, Sparkles } from "lucide-react";

import { Eyebrow } from "@/components/ui/eyebrow";
import { Pill } from "@/components/ui/pill";
import type { ShowcaseRepoMetrics } from "@/lib/api/public-client";

import { compact, relativeTime, usd } from "./format";

function Stat({ label, value, title }: { label: string; value: string; title?: string }) {
  return (
    <div className="flex flex-col gap-0.5" title={title}>
      <span className="text-lg font-semibold leading-none tracking-tight text-[var(--text)] tabular-nums">
        {value}
      </span>
      <Eyebrow className="font-medium">{label}</Eyebrow>
    </div>
  );
}

function KnowledgeModels({ metrics }: { metrics: ShowcaseRepoMetrics }) {
  const models = metrics.knowledge_models;
  if (models.length === 0) return null;
  const names = models.map((x) => x.model);
  return (
    <span
      className="inline-flex items-center gap-1.5 rounded-full bg-[var(--surface-2)] px-2.5 py-1 text-[var(--text-muted)]"
      title={`Knowledge generated by: ${names.join(", ")}`}
    >
      <Sparkles className="size-3.5 text-[var(--primary)]" aria-hidden />
      <span className="text-[var(--text-subtle)]">Generated by</span>
      <span className="font-medium text-[var(--text)]">{names[0]}</span>
      {names.length > 1 && <span className="text-[var(--text-subtle)]">+{names.length - 1}</span>}
    </span>
  );
}

export function ShowcaseMetricsBar({ metrics }: { metrics: ShowcaseRepoMetrics }) {
  const m = metrics;
  return (
    <div className="glass-chrome flex flex-col gap-4 rounded-lg px-4 py-4">
      <div className="flex flex-wrap items-end gap-x-8 gap-y-4">
        <Stat label="Lines of code" value={compact(m.lines_of_code)} title={`${m.lines_of_code.toLocaleString()} LOC`} />
        <Stat label="Knowledge nodes" value={compact(m.node_count)} />
        <Stat label="Relationships" value={compact(m.edge_count)} />
        {m.exports > 0 && <Stat label="Public exports" value={compact(m.exports)} />}
        <Stat
          label="Indexing cost"
          value={usd(m.ingest_cost_usd)}
          title="Total LLM spend Athena used to generate this knowledge"
        />
      </div>
      <div className="flex flex-wrap items-center gap-2 text-xs text-[var(--text-muted)]">
        <KnowledgeModels metrics={m} />
        {m.primary_language && <Pill tone="primary">{m.primary_language}</Pill>}
        {m.architectural_pattern && <Pill tone="primary">{m.architectural_pattern}</Pill>}
        {m.commit_short && (
          <span className="inline-flex items-center gap-1 font-mono">
            <GitCommit className="size-3.5" aria-hidden /> {m.commit_short}
          </span>
        )}
        {m.last_synced_at && (
          <span className="inline-flex items-center gap-1">
            <Clock className="size-3.5" aria-hidden /> indexed {relativeTime(m.last_synced_at)}
          </span>
        )}
      </div>
    </div>
  );
}
